
defaults:
  - _self_
  # - model: gru_audio
  - model: gru_audio
  - dataset: ucf101


batch_size: 16
num_workers: 4

epochs: 20
max_epochs: 10

seed: 13

data_subset: True

wandb:
  project: "cor-hip"
  config:
    batch_size: 32
    epochs: 20
    model_name: gru_audio
  


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: .  
  job:
    chdir: False

  # output_subdir: ./logs  # Subdirectory for outputs
  # job_logging:
  #   level: INFO  # Set desired log level (DEBUG, INFO, WARNING, etc.)