
defaults:
  - model: gru_audio
  - dataset: ufc101


batch_size: 32
batch_size_val: 1
epochs: 20
max_epochs: 10

seed: 13


wandb:
  project: "cor-hip"
  config:
    batch_size: 32
    epochs: 20
    model_name: gru_audio
  

