
defaults:
  - _self_
  - model: gru_audio
  - dataset: ucf101


batch_size: 32
batch_size_val: 1
epochs: 20
max_epochs: 10

seed: 13

data_subset: True

wandb:
  project: "cor-hip"
  config:
    batch_size: 32
    epochs: 20
    model_name: gru_audio
  

hydra:
  run:
    dir: .
  job:
    chdir: False